#suppress inspection "UnusedProperty" for whole file
.longName=Starwing Omen
.name=
~01~~panel_001~1_narration=Darkness. The absence of sight.
~01~~panel_002~1_narration=A lazy hum fills <hero.namePossessive> being.
~01~~panel_003~1_narration=Flickering.
~01~~panel_004~1_narration=An animated flame, crawling, ever so slowly, [white]inexorably[] -
~01~~panel_005~1_narration=from a perch amid nothingness
~01~~panel_006~1_narration=down a wick of unreality
~01~~panel_007~1_narration=into the stuff of [white]being[].
~01~~panel_008~1_narration=Greedily seizing, absorbing, fashioning...
~01~~panel_008~2_narration=...from the starstuff and the darkness between...
~01~~panel_008~3_narration=...a carapace, a body, a self.
~01~~panel_009~1_narration=<hero> turns over uneasily in <hero.mf:his/her/their> sleep.
~01~~panel_010~1_narration=Did new stars blossom in the sky that night?
~01~~panel_010~2_narration=Or have they winked out?
~01~~panel_011.(hook_exists)~1_narration=Elsewhere entirely, <hook> is floating on the whims of <hook.mf:his/her/their> dreamwise mind.
~01~~panel_012.(hook_exists)~1_hook=<hook.personality:It's like in On the Wings of Glindergast... \nor was it Winds? [i]"Violet mists left pearls of dew. In their wake, onwards I flew..."[][face:talking]/It's so nice knowing there are no \nmonsters in bushes here.[face:interested]/Why bother flying when you can \nget a cloud to do it for you?/I should really find some wings \nin the waking world sometime.[face:interested]\nHard to come by, unfortunately./If only the others could see \nthis. Experience it as I do.[face:interested]/And now, for a skydive...[face:joy]/If only the others could see this. Would \nthey even believe me if I told them?[face:joy]/[face:joy]This is wonderful. Just me and the wind.../[i]Violet mists left pearls of dew. \nIn their wake, onwards I flew.[][face:talking]/Imagine floating like this with your \nbeloved, touching the sky together...[face:interested]/Why bother flying when you can \nget a cloud to do it for you? >
~01~~panel_013.(hook_exists)~1_narration=The dream changes...
~01~~panel_014.(hook_exists)~1_narration=... and fate tosses <hook.mf:him/her/them> into a vortex of dreadful possibility.
~01~~panel_014.(hook_exists)~2_narration=Images and sensations flash, howl, twist into a single snarl, almost impossible to comprehend.
~01~~panel_015.(hook_exists)~1_narration=Doom falling from the sky.
~01~~panel_016.(hook_exists)~1_narration=One dark seed raining countless others.
~01~~panel_017.(hook_exists)~1_narration=The very air ripped and repurposed into weaving nightmares for those below.
~01~~panel_018.(hook_exists)~1_narration=Wide awake and yawning only a little, <loner> stargazes.
~01~~panel_018.(hook_exists)~2_loner=<loner.theme_star:[gray]... you know what it's like, Sennya. I can't sleep when I could be watching you instead./>
~01~~panel_019.(hook_is_missing)~1_narration=Elsewhere entirely, wide awake and yawning only a little, <loner> stargazes.
~01~~panel_020~1_narration=Until a streak of light is born before <loner.mf:his/her/their> eyes.
~01~~panel_021~1_narration=Greenbright and gloaming, it casts everything in bleak, unreal shine.
~01~~panel_021~2_loner=<loner.theme_star:[gray]Sennya?!/>
~01~~panel_022~1_narration=An oilslick, staining the world in its colours.
~01~~panel_023~1_narration=The comet fades with the dawn. But it will be there the next night, and the next.
~01~~panel_024~1_narration=And <company> will be there, too.\nChasing the Thrixl sightings in its wake.
