#suppress inspection "UnusedProperty" for whole file
.longName=Malthides Keystone Victory
.name=
~01~~panel_001~1_narration=It's a hill library of the kind quiet-loving scholars make. \nIt's not an uncommon thing to find, isolated.
