#suppress inspection "UnusedProperty" for whole file
.longName=Malthides Capstone
.name=
~01~prompt~panel_001~1_narration=The morning of the day <hero2.exists:they're/<hero.mf:he's/she's/they're>> set to arrive at the great library, <hero3.exists:<hero3>/<hero>> notices an unsure shadow haunting <hero2.exists:the/<hero.mf:his/her/their>> camp.
~02~choice_one~panel_001~1_narration=Committed but cautious, <hero2.exists:they break themselves/<hero> breaks <hero.mf:himself/herself/themself>> an entrance.
~02~choice_one~panel_001~2_darken=+Fortitude
~03~choice_two~panel_001~1_narration=<hero2.exists:They bash/<hero> bashes> a hole in the building, deciding speed will serve <hero2.exists:them/<hero.mf:him/her/them>> best.
~03~choice_two~panel_001~2_darken=+Haste
~03~choice_two~panel_001~3_action=[actionSmall][brown]crack!
~03~choice_two~panel_001~4_action=[actionSmall][brown]brackle!
